livereload = true
gtag = "G-MHF58SREPL"
title = "Menos Relato"
favicon = "assets/img/favicon.ico"

css = [
  "https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css",
  "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css",
  "https://rawgit.com/vitmalina/w2ui/master/dist/w2ui.min.css",
  "/assets/css/site.css",
]

js = [
  "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js",
  "https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js",
  "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/js/all.min.js",
  "https://cdn.anychart.com/releases/v8/js/anychart-base.min.js",
  "https://cdn.anychart.com/releases/v8/js/anychart-tag-cloud.min.js",
  "https://rawgit.com/vitmalina/w2ui/master/dist/w2ui.js",
]

networks = [
  { icon = "icons/x.svg", url = "https://x.com/MenosRelato", title = "X/Twitter" },
  { icon = "icons/medium.svg", url = "https://medium.com/@MenosRelato", title = "Blog @ Medium" },
  { icon = "icons/youtube.svg", url = "https://youtube.com/@MenosRelato", title = "YouTube" },
  { icon = "icons/github.svg", url = "https://github.com/MenosRelato/conicet", title = "Código @ GitHub" }
]